Plant.create(name: "Sweet Corn", description: "Good enough to eat right off the plant when picked at peak ripeness. Once standard sweet corn is picked its sugar changes to starch quickly. By rushing ears from the garden to boiling water, you can capture their full sweetness.")
Plant.create(name: "Cucumber", description: "A staple for salads, soups, and appetizers.")
Plant.create(name: "Eggplant", description: "Delicious when grilled in olive oil, or paired with ripe tomatoes in Eggplant Parmigiana.")
Plant.create(name: "Canteloupe", description: "Cantaloupes taste so sweet and juicy when fully ripe, they’re worth the long wait―4 months of steady heat― to harvest.")
Plant.create(name: "Jalapeño", description: "A classic pepper that adds a bit of spice to any dish.")
Plant.create(name: "Tomato", description: "Great all-purpose vegetable (or a fruit, technically) that is versatile enough to be able to use in just about anything.")
Plant.create(name: "Watermelon", description: "A summer staple! What's a summer picnic without a watermelon?")
Plant.create(name: "Zucchini", description: "Easy to grow, and you can eat both the fruits and blossoms. ")
Plant.create(name: "Cilantro", description: "Tender leaves of this tap-rooted annual are indespensible for flavoring guacamole, salsas, gazpacho, and more. Cilantro is easy to grow from seed in low, wide bowls; you just snip off outer leaves when plant reach about 8 inches tall.")
Plant.create(name: "Basil", description: "Great for making pesto and bruschetta, dropping into tomato salads and more. Glossy green leaves make showy garnishes, too.")
Plant.create(name: "Mint", description: "Many different varieties, but all have a wonderful scent and are great in aromatic dishes.")
Plant.create(name: "Sage", description: "Leaves of this shrubby perennial are flavorful and aromatic.")
Plant.create(name: "Blueberry", description: "These berries have a delicious sweet-tart flavor, and they’re high in antioxidents.")
Plant.create(name: "Strawberry", description: "Few things taste sweeter than a plump, sun-warmed strawberry picked at peak of ripeness; it’s dessert right off the plant.")
Plant.create(name: "Leaf Lettuce", description: "All leaf lettuces (ones that grow in loose rosettes rather than heads) are great in salads. Fresh cut as baby greens, they’re sweet and tender.")
Plant.create(name: "Radish", description: "This root crop is super easy to grow―and very fast!")
Plant.create(name: "Swiss Chard", description: "Leaves and stems are pretty in pots and garden beds, they taste great in soups and stir fries, and the plant produces over a long season.")
Plant.create(name: "Snow Peas", description: "A must-have plant for a cool-season garden. Pods are tasty in stir fries, and they add crunch to salads.")
Plant.create(name: "Lacinato Kale", description: "Extra hardy, and tasty in a variety of dishes (try pan-frying them in extra virgin olive oil with lemon and red chile flakes).")
Garden.create(name: "The Iron Garden")
Garden.create(name: "Neighborhood Garden")
User.create(first_name: "John", last_name: "Smith", password: "password", email: "johnsmith@example.com", garden_id: 1)
User.create(first_name: "Naomi", last_name: "Ruiz", password: "password", email: "nruiz@example.com", garden_id: 1)
User.create(first_name: "Rosie", last_name: "Johnson", password: "password", email: "rosie@example.com", garden_id: 1)
User.create(first_name: "Lamar", last_name: "Smith", password: "password", email: "l.smith@example.com", garden_id: 1)
User.create(first_name: "Jeff", last_name: "Young", password: "password", email: "jeffyoung@example.com", garden_id: 1)
User.create(first_name: "Jennifer", last_name: "Anderson", password: "password", email: "j.anderson@example.com", garden_id: 1)
User.create(first_name: "Joanna", last_name: "Kowalski", password: "password", email: "jo.kowalski@example.com", garden_id: 1)
Plot.create(garden_id: 1, user_id: 1, plot_number: 1)
Plot.create(garden_id: 1, user_id: 2, plot_number: 2)
Plot.create(garden_id: 1, user_id: 3, plot_number: 3)
Plot.create(garden_id: 1, user_id: 4, plot_number: 4)
Plot.create(garden_id: 1, user_id: 5, plot_number: 5)
Plot.create(garden_id: 1, user_id: 6, plot_number: 6)
Plot.create(garden_id: 1, user_id: 7, plot_number: 7)
